const char* _river[] = {
    "AS YOU WALK",
    "YOU HEAR THE",
    "SOUND OF",
    "RUSHING WATER",
    "BREAK",
    "A LARGE OLD",
    "BRIDGE REACHES",
    "ACROSS THE",
    "WATER",
    "BREAK",
    "THAT DOESN'T",
    "LOOK SAFE!",
    "BREAK",
    "AS YOU STEP",
    "ONTO THE",
    "BRIDGE",
    "THE WIND",
    "RUSHES THROUGH",
    "YOUR HAIR,",
    "AS IF SOME",
    "GREATER FORCE",
    "IS TRYING",
    "TO PUSH",
    "YOU INTO",
    "THE HEAVY",
    "FLOW",
    "BREAK",
    "KUPALA",
    "PROTECT ME!",
    "BREAK",
    "THERE IS",
    "A SUDDEN",
    "MIGHTY RUSH",
    "OF WIND",
    "AND AS YOU",
    "STUMBLE TO",
    "CATCH YOUR",
    "FEET, THE",
    "WOOD GIVES",
    "WAY UNDER",
    "YOU AND YOU",
    "PLUNGE INTO",
    "THE ICY",
    "DEPTHS",
    "BREAK",
    "HELP! HELP",
    "I CAN'T SWIM",
    "BREAK",
    "WITH YOUR",
    "LAST BREATH",
    "YOU SCREAM",
    "WITH",
    "DESPERATION",
    "BREAK",
    "HEEEELLLLLP!",
    "BREAK",
    "AS YOU SINK",
    "UNDER YOU",
    "FEEL THE COLD",
    "GRASP OF HANDS",
    "WRAP AROUND",
    "YOUR THROAT,",
    "DRAGGING YOU",
    "UNDER",
    "BREAK",
    "THE LIFE",
    "SEEPS FROM",
    "YOUR BODY",
    "AND",
    "EVERYTHING",
    "TURNS BLACK",
    "BREAK",
    "YOU FEEL YOUR",
    "EYES OPEN",
    "SLOWLY",
    "BREAK",
    "WHERE AM I?",
    "BREAK",
    "IT IS LUCKY",
    "I HEARD YOU",
    "YELLING",
    "BREAK",
    "IT TAKES",
    "YOU SOME TIME",
    "TO RECOGNISE",
    "THE PERSON",
    "IN FRONT OF YOU",
    "BREAK",
    "FATHER!",
    "BREAK",
    "I WAS SO",
    "WORRIED!",
    " ",
    "YOU KNOW",
    "NEVER TO GO",
    "TO THE WOODS",
    "IN THE DARK",
    "BREAK",
    "BUT FATHER",
    "STEPMOTHER",
    "TOLD ME T..",
    "BREAK",
    "HE CUTS YOU",
    "OFF SHARPLY",
    "BREAK",
    "I WILL NOT",
    "HEAR IT!",
    " ",
    "YOU ARE",
    "NEVER TO",
    "LEAVE HOME",
    "IN THE DARK",
    " ",
    "DO YOU",
    "UNDERSTAND?"
};