const char* _beginning[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "BREAK",
    "YOU: MOTHER?",
    "BREAK",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    " ",
    "HAVE YOU BROUGHT",
    "THE BRUSHWOOD?",
    "BREAK",
    "YES MOTHER",
    "BREAK",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "BREAK",
    "...",
    " ",
    "BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "BREAK",
    "YOU WILL DO",
    "AS I ASK!",
    "BREAK",
    "...",
    " ",
    "YES MOTHER",
    "BREAK",
    "YOU SET OUT",
    "TO THE WELL",
    "BUT WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    " ",
    "YOU ARE MORE",
    "LOST THAN EVER",
    "BREAK",
    "AS YOU WALK",
    "YOU COME ACROSS",
    "FOOTSTEPS IN",
    "THE GROUND",
    "END"
};

const char* _footprints[] = {
    "AS YOU WALK",
    "YOU NOTICE",
    "THE FLOOR IS",
    "GETTING STICKY",
    "BREAK",
    "EW, MY BOOTS",
    "ARE COVERED IN",
    "MUD!",
    "BREAK",
    "YOU HEAR A",
    "VOICE FROM",
    "THE TREES",
    "BREAK",
    "...",
    " ",
    "W-WH-WHO",
    "WHO'S THERE?",
    "BREAK",
    "OH MY SWEET",
    "LITTLE CHILD",
    "SO LOST IN",
    "THE MIDDLE",
    "OF MY FOREST",
    "BREAK",
    "DON'T BE",
    "AFRAID",
    " ",
    "BABAYAGA",
    "WILL SHOW",
    "YOU THE WAY",
    "BREAK",
    "BABAYAGA",
    "TAKES YOUR",
    "HAND AND",
    "LEADS YOU",
    "DEEP INTO",
    "THE FOREST",
    "BREAK",
    "GAME OVER",
    "END"
};