const char* _beginning[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "BREAK",
    "YOU: MOTHER?",
    "BREAK",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    " ",
    "HAVE YOU BROUGHT",
    "THE BRUSHWOOD?",
    "BREAK",
    "YES MOTHER",
    "BREAK",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "BREAK",
    "...",
    " ",
    "BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "BREAK",
    "YOU WILL DO",
    "AS I ASK!",
    "BREAK",
    "...",
    " ",
    "YES MOTHER",
    "BREAK",
    "YOU SET OUT",
    "TO THE WELL",
    "BUT WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    " ",
    "YOU ARE MORE",
    "LOST THAN EVER",
    "BREAK",
    "AS YOU WALK",
    "YOU COME ACROSS",
    "FOOTSTEPS IN",
    "THE GROUND",
    "END"
};

const char* _footprints[] = {
    "AS YOU WALK",
    "YOU NOTICE",
    "THE FLOOR IS",
    "GETTING STICKY",
    "BREAK",
    "EW, MY BOOTS",
    "ARE COVERED IN",
    "MUD!",
    "BREAK",
    "YOU HEAR A",
    "VOICE FROM",
    "THE TREES",
    "BREAK",
    "...",
    " ",
    "W-WH-WHO",
    "WHO'S THERE?",
    "BREAK",
    "OH MY SWEET",
    "LITTLE CHILD",
    "SO LOST IN",
    "THE MIDDLE",
    "OF MY FOREST",
    "BREAK",
    "DON'T BE",
    "AFRAID",
    " ",
    "BABAYAGA",
    "WILL SHOW",
    "YOU THE WAY",
    "BREAK",
    "BABAYAGA",
    "TAKES YOUR",
    "HAND AND",
    "LEADS YOU",
    "DEEP INTO",
    "THE FOREST",
    "BREAK",
    "GAME OVER",
    "END"
};

const char* _river[] = {
    "AS YOU WALK",
    "YOU HEAR THE",
    "SOUND OF",
    "RUSHING WATER",
    "BREAK",
    "A LARGE OLD",
    "BRIDGE REACHES",
    "ACROSS THE",
    "WATER",
    "BREAK",
    "THAT DOESN'T",
    "LOOK SAFE!",
    "BREAK",
    "AS YOU STEP",
    "ONTO THE",
    "BRIDGE",
    "THE WIND",
    "RUSHES THROUGH",
    "YOUR HAIR,",
    "AS IF SOME",
    "GREATER FORCE",
    "IS TRYING",
    "TO PUSH",
    "YOU INTO",
    "THE HEAVY",
    "FLOW",
    "BREAK",
    "KUPALA",
    "PROTECT ME!",
    "BREAK",
    "THERE IS",
    "A SUDDEN",
    "MIGHTY RUSH",
    "OF WIND",
    "AND AS YOU",
    "STUMBLE TO",
    "CATCH YOUR",
    "FEET, THE",
    "WOOD GIVES",
    "WAY UNDER",
    "YOU AND YOU",
    "PLUNGE INTO",
    "THE ICY",
    "DEPTHS",
    "BREAK",
    "HELP! HELP",
    "I CAN'T SWIM",
    "BREAK",
    "WITH YOUR",
    "LAST BREATH",
    "YOU SCREAM",
    "WITH",
    "DESPERATION",
    "BREAK",
    "HEEEELLLLLP!",
    "BREAK",
    "AS YOU SINK",
    "UNDER YOU",
    "FEEL THE COLD",
    "GRASP OF HANDS",
    "WRAP AROUND",
    "YOUR THROAT,",
    "DRAGGING YOU",
    "UNDER",
    "BREAK",
    "THE LIFE",
    "SEEPS FROM",
    "YOUR BODY",
    "AND",
    "EVERYTHING",
    "TURNS BLACK",
    "BREAK",
    "YOU FEEL YOUR",
    "EYES OPEN",
    "SLOWLY",
    "BREAK",
    "WHERE AM I?",
    "BREAK",
    "IT IS LUCKY",
    "I HEARD YOU",
    "YELLING",
    "BREAK",
    "IT TAKES",
    "YOU SOME TIME",
    "TO RECOGNISE",
    "THE PERSON",
    "IN FRONT OF YOU",
    "BREAK",
    "FATHER!",
    "BREAK",
    "I WAS SO",
    "WORRIED!",
    " ",
    "YOU KNOW",
    "NEVER TO GO",
    "TO THE WOODS",
    "IN THE DARK",
    "BREAK",
    "BUT FATHER",
    "STEPMOTHER",
    "TOLD ME T..",
    "BREAK",
    "HE CUTS YOU",
    "OFF SHARPLY",
    "BREAK",
    "I WILL NOT",
    "HEAR IT!",
    " ",
    "YOU ARE",
    "NEVER TO",
    "LEAVE HOME",
    "IN THE DARK",
    " ",
    "DO YOU",
    "UNDERSTAND?"
};