const char* beginning[] = {
    "FAR, FAR AWAY",
    "OVER HILL,",
    "OVER DALE,",
    "LIVED A LITTLE",
    "CHILD JUST",
    "LIKE YOU",
    "BREAK",
    "YOU: MOTHER?",
    "BREAK",
    "STEPMOTHER: OH!",
    "IT'S YOU!",
    " ",
    "HAVE YOU BROUGHT",
    "THE BRUSHWOOD?",
    "BREAK",
    "YES MOTHER",
    "BREAK",
    "GOOD! NOW WILL",
    "YOU GO FETCH",
    "SOME WATER?",
    "BREAK",
    "...",
    " ",
    "BUT MOTHER",
    "THE SUN IS",
    "SETTING DEEP IN",
    "THE WOODS",
    "BREAK",
    "YOU WILL DO",
    "AS I ASK!",
    "BREAK",
    "...",
    " ",
    "YES MOTHER",
    "BREAK",
    "YOU SET OUT",
    "TO THE WELL",
    "BUT WHEN YOU",
    "REACH IT THE",
    "SUN HAS ALREADY",
    "SET",
    " ",
    "YOU ARE MORE",
    "LOST THAN EVER",
    "BREAK",
    "AS YOU WALK",
    "YOU COME ACROSS",
    "FOOTSTEPS IN",
    "THE GROUND",
    "END"
};

const char* footprints[] = {
    "YOU ENTER A",
    "CLEARING AND",
    "SEE A JAR ON",
    "THE FLOOR",
    "YOU THINK FOR",
    "A SECOND AND",
    "THEN PICK IT",
    "UP",
    "OUT OF THE",
    "CORNER OF YOUR",
    "EYE YOU SEE A",
    "BRIGHT GLOW",
    " ",
    "AS YOU",
    "APPROACH YOU",
    "REALISE IT IS",
    "A SMALL BALL",
    "OF FIRE",
    " ",
    "YOU OFFER OUT",
    "THE JAR AND",
    "THE FIRE MOVES",
    "INSIDE",
    "ANOTHER BALL",
    "OF FIRE",
    " ",
    "...",
    " ",
    "INTERESTING",
    " ",
    "...",
    " ",
    "YOU PUT IT",
    "IT IN YOUR",
    "JAR",
    "YOU FIND A",
    "THIRD BALL OF",
    "FIRE AND THIS",
    "TIME IT GIVES",
    "ENOUGH LIGHT",
    "THAT YOU SPOT",
    "FOOTSTEPS",
    "LEADING OUT OF",
    "THE CLEARING",
    "FOLLOW THE",
    "FOOTSTEPS?",
    "AS YOU WALK",
    "YOU NOTICE THE",
    "GROUND GETTING",
    "STICKY",
    "EW! MY BOOTS",
    "ARE ALL IN MUD",
    "YOU HEAR A",
    "SOUND IN THE",
    "TREES",
    "WHO'S THERE?!",
    "HELLO, LITTLE ONE",
    "W-W-WHO?",
    "WHO ARE YOU?",
    "OH, MY SWEET",
    "LITTLE ONE",
    " ",
    "I AM BABA YAGA",
    "BABA YAGA",
    "TAKES YOUR HAND",
    "AND LEADS YOU",
    "DEEP INTO THE",
    "FOREST....",
    "GAME OVER!",
    "AS YOU WALK",
    "YOU COME ACROSS",
    "A RIVER",
    "DO YOU WANT",
    "TO CROSS?",
    "AS YOU STEP ON",
    "THE BRIDGE IT",
    "GIVES WAY",
    "BENEATH YOU",
    " ",
    "YOU CRASH INTO",
    "THE WATER",
    " ",
    "AS YOU TRY TO",
    "SWIM TO THE",
    "SURFACE YOU",
    "FEEL CURRENTS",
    "ON YOUR LEGS",
    "DRAGGING YOU",
    "DOWN",
    " ",
    " ",
    "GASPING FOR",
    "AIR YOU ARE",
    "SUDDENLY",
    "DRAGGED FROM",
    "THE WATER",
    "WHAT DO YOU",
    "THINK YOU",
    "ARE DOING?!",
    "FATHER!",
    "DON'T YOU",
    "KNOW IT IS",
    "DANGEROUS IN",
    "THE WOODS",
    "AT NIGHT?"
};